import { any, route } from './router.js';
import { handleAuthLogin } from './handlers/auth/login.js';
import { handleAuthLogout } from './handlers/auth/logout.js';
import { handleAuthRefresh } from './handlers/auth/refresh.js';
import { handleAuthRegister } from './handlers/auth/register.js';
import { handleHealth } from './handlers/health.js';
import { handleApiHealth } from './handlers/apiHealth.js';
import { handleApiMe } from './handlers/apiMe.js';
import { handleApiChatsList } from './handlers/chats/listChats.js';
import { handleApiChatGet } from './handlers/chats/getChat.js';
import { handleApiChatMessagesList } from './handlers/chats/listMessages.js';
import { handleApiChatOpen } from './handlers/chats/openChat.js';
import { handleApiChatsSearch } from './handlers/chats/searchChats.js';
import { handleApiChatSend } from './handlers/chats/sendMessage.js';
import { handleApiChatSendToChat } from './handlers/chats/sendMessageToChat.js';
import { handleApiChatMarkRead } from './handlers/chats/markRead.js';

any('/', handleHealth);
any('/health', handleHealth);
route(['GET', 'HEAD'], '/api/health', handleApiHealth);
route(['GET', 'HEAD'], '/api/me', handleApiMe);
route(['POST'], '/api/login', handleAuthLogin);
route(['POST'], '/api/auth/login', handleAuthLogin);
route(['POST'], '/api/auth/refresh', handleAuthRefresh);
route(['POST'], '/api/logout', handleAuthLogout);
route(['POST'], '/api/register', handleAuthRegister);
route(['GET', 'HEAD'], '/api/chats', handleApiChatsList);
route(['GET', 'HEAD'], '/api/chats/search', handleApiChatsSearch);
route(['GET', 'HEAD'], '/api/chats/:chatId', handleApiChatGet);
route(['GET', 'HEAD'], '/api/chats/:chatId/open', handleApiChatOpen);
route(['GET', 'HEAD'], '/api/chats/:chatId/messages', handleApiChatMessagesList);
route(['POST'], '/api/chats/:chatId/messages', handleApiChatSendToChat);
route(['POST'], '/api/chats/:chatId/read', handleApiChatMarkRead);
route(['POST'], '/api/chat/send', handleApiChatSend);

export { match } from './router.js';
