export const MessageType = {
  HELLO: 'HELLO',
  HELLO_ACK: 'HELLO_ACK',
  PING: 'PING',
  PONG: 'PONG',
  MESSAGE_RECEIVE: 'MESSAGE_RECEIVE',
  MESSAGE_READ: 'MESSAGE_READ',
  MESSAGE_READ_CONFIRM: 'MESSAGE_READ_CONFIRM',
  MESSAGE_DELIVERED: 'MESSAGE_DELIVERED',
  MESSAGE_DELIVERED_CONFIRM: 'MESSAGE_DELIVERED_CONFIRM',
  MESSAGE_STATE_UPDATE: 'MESSAGE_STATE_UPDATE',
  MESSAGE_ERROR: 'MESSAGE_ERROR',
  TYPING_START: 'TYPING_START',
  TYPING_STOP: 'TYPING_STOP',
  PRESENCE: 'PRESENCE',
  PRESENCE_LIST: 'PRESENCE_LIST',
  PRESENCE_SNAPSHOT: 'PRESENCE_SNAPSHOT',
  ERROR: 'ERROR',
};

export const CloseCodes = {
  NORMAL: 1000,
  GOING_AWAY: 1001,
  PROTOCOL_ERROR: 1002,
  UNSUPPORTED: 1003,
  INVALID_PAYLOAD: 1007,
  POLICY_VIOLATION: 1008,
  INTERNAL_ERROR: 1011,
  UNAUTHORIZED: 4401,
  TOKEN_EXPIRED: 4402,
  INVALID_TOKEN: 4403,
  RATE_LIMIT: 4008,
};

export const PROTOCOL_VERSION = 1;
